name: a workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my_first_job:
    name: first job
    runs-on: ubuntu-18.04
    steps:
      - name: greeting pigeon377
        env: 
          greeting: greet
          name : pigeon377
        run:
          echo $greeting $name !
